### ISSUE TITLE
Configuration doesn't match with collections

### ISSUE THREAD

**Issue by reinij** [nlsfi/hakunapi#124]
Configuration in properties is defined as follows and works with URL's, but in UI shows incorrectly

![image](https://github.com/user-attachments/assets/8bfb41f5-a27f-49a5-8096-ea9ec7cd8176)

![image](https://github.com/user-attachments/assets/00860227-a0f9-42dd-9625-65d96eacd7d6)

**Comment by jampukka** [comment]
Title can be overridden in configuration for all sources via .title property, e.g.:
`collections.osoitteet.title=Osoitteet`

Usually hakunapi defaults to the technical collection identifier (`osoitteet` here) but for source-gpkg it's considered a feature that value from `gpkg_contents.identifier` is used as the default if available (it's unique but nullable).

**Comment by reinij** [comment]
Thx - my mistake.
