### ISSUE TITLE
Java version support (JDK11 and JDK17)

### ISSUE THREAD

**Issue by teezip** [nlsfi/hakunapi#17]
Previous versions of Hakunapi supported also Java 8 - this can be removed.

Requirements for Java version support (minimum):
* JDK11
* JDK17

Also related to #16 other java servlet related requirements:
* currently the main target: JDK11+ / tomcat 9 / jersey 2 / javax / webapp 
* in the future maybe also: JDK11+ / tomcat 10 / jersey 3 /jakarta / webapp

**Comment by teezip** [comment]
See PR #21 (Drop support for Java 8)

**Comment by jampukka** [comment]
Completed in #21

**Comment by jampukka** [comment]
This issue is now completed. upcoming hakunapi release (0.2.0, or 1.0.0) will require Java >=11
