### ISSUE TITLE
Publish the demo service in an open endpoint

### ISSUE THREAD

**Issue by teezip** [nlsfi/hakunapi#18]
After #10 is finalized on the repository and tested locally.

To publish a server for OGC API demos by NLS of Finland is used.

**Comment by teezip** [comment]
Weekly 27.3.2023 : not yet installed, waiting for #10 to be completed

**Comment by reinij** [comment]
If this one (https://beta-paikkatieto.maanmittauslaitos.fi/inspire-addresses/features/v1/) will be used as a demo, please note:

JSON encoding (f=json) is broken or not used in
https://beta-paikkatieto.maanmittauslaitos.fi/inspire-addresses/features/v1/collections
https://beta-paikkatieto.maanmittauslaitos.fi/inspire-addresses/features/v1/collections/addresses

but f=json works in …/items
https://beta-paikkatieto.maanmittauslaitos.fi/inspire-addresses/features/v1/collections/addresses/items?f=json

**Comment by teezip** [comment]
The demo implementation behind https://beta-paikkatieto.maanmittauslaitos.fi/inspire-addresses/features/v1/ is now the demo of Hakunapi called "finnish-addresses" implemented in https://github.com/nlsfi/hakunapi/pull/20

**Comment by jampukka** [comment]
This could probably be implemented pretty easily throughout current JAX-RS implementation with a pre-matching filter.
