### ISSUE TITLE
Analyze use cases and implementation choices for supporting OGC Features and Geometries JSON

### ISSUE THREAD

**Issue by teezip** [nlsfi/hakunapi#26]
## Background

See the official github page about: [OGC Features and Geometries JSON](https://github.com/opengeospatial/ogc-feat-geo-json) that is [OGC](https://www.ogc.org/)'s **candidate standard**.

According to documentation *OGC Features and Geometries JSON* will

* include the ability to use Coordinate Reference Systems (CRSs) other than WGS84
* follow the [OGC Axis Order Policy](https://portal.opengeospatial.org/files/?artifact_id=76024),
* allow the use of non-Euclidean metrics, in particular ellipsoidal metrics,
* support solids and multi-solids as geometry types, and
* provide guidance on how to represent feature properties, e.g., including temporal properties.

This might be one of candidate enhancements for Hakunapi after 1.0 version.

Before deciding some analysis is needed:
* use cases and data sets for new geometry types like solids and multi-solids
* how new capabilities of OGC Features and Geometries JSON would be used in vector data products or geospatial APIs by mapping agencies like NLS of Finland
* how to define, implement and document application schemas when producing OGC API Features service that supports 1) GeoJSON content with CRS84 default coordinate system, 2) GeoJSON content with other coordinate systems according to OGC API Features Part 2 (CRS) and it's "Content-Crs" header (that provides also a method for axis-order issue), 3) JSON-FG content with CRS84 (content is same as GeoJSON) or other coordinate systems (content is something different to GeoJSON content)
* implementation choices in Hakunapi (there's some internal notes by NLS of Finland on this topic)

## Suggested first implementation targeting Hakunapi 1.1.0 version

Support at least these features first:
* include the ability to use Coordinate Reference Systems (CRSs) other than WGS84
* follow the [OGC Axis Order Policy](https://portal.opengeospatial.org/files/?artifact_id=76024),
* provide guidance on how to represent feature properties, e.g., including temporal properties.

Non goals (for first iteration):
* allow the use of non-Euclidean metrics, in particular ellipsoidal metrics,
* support solids and multi-solids as geometry types, and

Standard conformance classes to be supported (from the draft standard):

* "Core": The Core conformance class extends GeoJSON with additional members that allow [Temporal information](https://docs.ogc.org/DRAFTS/21-045.html#time), extended [Geometry](https://docs.ogc.org/DRAFTS/21-045.html#place) information (i.e. geometries in coordinate reference systems (CRS) other than CRS84 which is the GeoJSON CRS, and additional geometry types) and [Reference systems](https://docs.ogc.org/DRAFTS/21-045.html#ref-sys) information to be encoded in a JSON-FG document. The Core conformance class has a dependency on GeoJSON. This means that a JSON-FG document that conforms to Core must also conform to GeoJSON.

**Comment by reinij** [comment]
INSPIRE is currently accepting OGC API Features as an interface for Download services. However, only endorsed encodings are GML and GeoPackage.

Some good reasons implement JSON-FG and ask endorsement from European Commission:

- JSON-FG supports coordinate reference systems other than WGS-84
- JSON-FG is backward compatible (if geometry is populated) and therefore works also with tools supporting only GeoJSON
- JSON-FG supports more complex geometry types, which are needed e.g. in TN (Transport Network)
- NLS-FI is using EPSG:3067 in GeoJSON (which is not valid GeoJSON)

I would start with INSPIRE AD (which is already used as an example of hakunapi) even if though it only has point as a geometry type.

**Comment by teezip** [comment]
Just linking this issue to the initial implementation PR #73 that's still under development.

**Comment by teezip** [comment]
Pre-release 1.3.0-rc1 (https://github.com/nlsfi/hakunapi/releases/tag/1.3.0-rc1) supports now JSON-FG output.

Demo-service has this pre-release now installed.

For example JSONFG output in WGS84 lon-lat default coordinate reference system (CRS84) has `geometry` just like GeoJSON:

https://beta-paikkatieto.maanmittauslaitos.fi/inspire-addresses/features/v1/collections/addresses/items?limit=1&f=jsonfg

`"geometry":{"type":"Point","coordinates":[23.2125784,62.9749241]}`

WGS84 lat-lon non-default (EPSG:4326) has `place` with `geometry`:

https://beta-paikkatieto.maanmittauslaitos.fi/inspire-addresses/features/v1/collections/addresses/items?limit=1&f=jsonfg&crs=http://www.opengis.net/def/crs/EPSG/0/4326

``"place":{"type":"Point","coordinates":[23.2125784,62.9749241]}`
`"geometry":{"type":"Point","coordinates":[23.2125784,62.9749241]}`

Maybe `place` should have coordinate azed in different way?

ETRS-TM35FIN seems to be ok, however different rounding?

https://beta-paikkatieto.maanmittauslaitos.fi/inspire-addresses/features/v1/collections/addresses/items?limit=1&f=jsonfg&crs=http://www.opengis.net/def/crs/EPSG/0/3067

`"place":{"type":"Point","coordinates":[308075,6988449]}`
`"geometry":{"type":"Point","coordinates":[23.213,62.975]}`
