### ISSUE TITLE
Update OGC API Features implementation list 

### ISSUE THREAD

**Issue by teezip** [nlsfi/hakunapi#40]
https://github.com/opengeospatial/ogcapi-features/tree/master/implementations
https://github.com/opengeospatial/ogcapi-features/blob/master/implementations/servers/nlsfi.md

**Comment by jampukka** [comment]
https://github.com/opengeospatial/ogcapi-features/pull/858

**Comment by teezip** [comment]
This pages seems to be updated now:
https://github.com/opengeospatial/ogcapi-features/blob/master/implementations/servers/hakunapi.md

However OGC API Features server implementations index page has broken link to "nlsfi" not listing "hakunapi".

**Comment by jampukka** [comment]
You're right, seems I only fixed the link in /implementations (https://github.com/opengeospatial/ogcapi-features/blob/master/implementations/README.adoc#servers) and missed the one in /implementations/servers. I'll fix it

**Comment by teezip** [comment]
All index pages in opengeospatial/ogcapi-features OK now. Closing this.
